const config = {
  DATABASE_CONNECTION: 'DATABASE_CONNECTION',
  DATABASE_CONNECTION_URL: 'mongodb://localhost:27017/abdullah',
  USER_MODEL: 'USER_MODEL',
  SENDING_EMAIL_HOST: 'smtp.mailtrap.io',
  SENDING_EMAIL_PORT: 2525,
  SENDING_EMAIL_USER: 'e1b7dc2655c974',
  SENDING_EMAIL_PASS: '6a65fb7e274b87',
  SENDING_EMAIL: 'nestjs@gupuboss.com',
  FORGET_PASSWORD_JWT_TOKEN_SECRET: 'FORGET_PASSWORD_JWT_TOKEN_SECRET',
  FORGET_PASSWORD_REDIRECT_URL_BACKEND: 'http://localhost:3001/forgetpassword/',
  FORGET_PASSWORD_REDIRECT_URL_FRONTEND: 'http://localhost:3000/forgetpassword/',
  RESET_PASSWORD_REDIRECT_URL_BACKEND: 'http://localhost:3001/resetpassword/',
  RESET_PASSWORD_JWT_TOKEN_SECRET: 'RESET_PASSWORD_JWT_TOKEN_SECRET',
  RESET_PASSWORD_REDIRECT_URL_FRONTEND: 'http://localhost:3000/resetpassword/'
}

export default config;